# Generated by Django 4.2.18 on 2025-01-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permisos', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permiso',
            field=models.ManyToManyField(related_name='roles', through='roles_permisos.RolPermiso', to='roles_permisos.permiso'),
        ),
    ]
