# Generated by Django 4.2.18 on 2025-01-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles_permisos', '0003_rol_permiso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='permiso',
            new_name='permisos',
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permiso_roles', to='roles_permisos.permiso'),
        ),
        migrations.AlterField(
            model_name='rolpermiso',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='roles_permisos.rol'),
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AlterModelTable(
            name='rolpermiso',
            table='roles_permisos_rolpermiso',
        ),
    ]
