# Generated by Django 4.2.17 on 2024-12-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espesor', models.FloatField()),
                ('largo', models.FloatField()),
                ('ancho', models.FloatField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
