# Generated by Django 4.2.17 on 2024-12-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancha',
            name='precio',
        ),
    ]
