# Generated by Django 4.2.17 on 2024-12-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espesor', models.FloatField()),
                ('largo', models.FloatField()),
                ('precio', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanchaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('plancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.plancha')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.proveedor')),
            ],
        ),
    ]
