# Generated by Django 4.2.17 on 2024-12-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_plegado_planchaproveedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plegado',
            new_name='CortePlegado',
        ),
    ]
