# Generated by Django 4.2.17 on 2024-12-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_rename_plegado_corteplegado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateField()),
                ('corte_plegado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.corteplegado')),
                ('plancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.plancha')),
            ],
        ),
    ]
