# Generated by Django 4.2.18 on 2025-01-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrol',
            table='users_userrol',
        ),
    ]
