# Generated by Django 4.2.18 on 2025-01-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='tipo',
            field=models.CharField(choices=[('aplicativo', 'Aplicativo'), ('seguridad', 'Seguridad')], max_length=200),
        ),
    ]
